### ISSUE TITLE
Renaming environments

### ISSUE THREAD

**Issue by gdgjkutdd** [jonasasx/envrouter#8]
I want to be able of renaming an environment (host name should remain unchanged) to better describe purpose of the environment.

**Comment by LlewLegato** [comment]
Это я, просто не под той учёткой запостил.

**Comment by jonasasx** [comment]
Environment can be set with Deployment label `envrouter.io/env=dev1`.

Example: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  namespace: default
  labels:
    envrouter.io/env=dev1
    envrouter.io/app: reflector
  annotations:
    envrouter.io/ref: main
    envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
spec:
  selector:
    matchLabels:
      app: reflector
  template:
    metadata:
      labels:
        app: reflector
        envrouter.io/app: reflector
      annotations:
        envrouter.io/ref: main
        envrouter.io/sha: 87cf26c39505769e5fcf8133417f36e1883650f0
    spec:
      containers:
        - name: reflector
          image: nginx:latest
```

The issue resolved in https://github.com/jonasasx/envrouter/releases/tag/v0.2.16 and https://github.com/jonasasx/envrouter-helm/releases/tag/envrouter-0.3.4
